/*
 * This source file was generated by the Gradle 'init' task
 */
package com.willtkelly;

import org.junit.Test;
import static org.junit.Assert.*;

import java.io.IOException;
import java.util.HashMap;


public class AppTest {
    @Test public void appHasAGreeting() {

    }
}
